In [1]:
import pandas as pd
import numpy as np
import missingno as msxo
import glob
import folium
import plotly.express as px

In [2]:
df_1 = pd.read_json('C:/Users/tomas/Desktop/DS - HENRY/00.LABS/3.PF/GOOGLE/metadata-sitios/1.json', lines= True)
df_1.head()

,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,relative_results,url
0,Porter Pharmacy,"Porter Pharmacy, 129 N Second St, Cochran, GA ...",0x88f16e41928ff687:0x883dad4fd048e8f8,None,32.388300,-83.357100,[Pharmacy],4.9,16,None,"[[Friday, 8AM–6PM], [Saturday, 8AM–12PM], [Sun...","{'Service options': ['In-store shopping', 'Sam...",Open ⋅ Closes 6PM,"[0x88f16e41929435cf:0x5b2532a2885e9ef6, 0x88f1...",https://www.google.com/maps/place//data=!4m2!3...
1,City Textile,"City Textile, 3001 E Pico Blvd, Los Angeles, C...",0x80c2c98c0e3c16fd:0x29ec8a728764fdf9,None,34.018891,-118.215290,[Textile exporter],4.5,6,None,None,None,Open now,"[0x80c2c624136ea88b:0xb0315367ed448771, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
2,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",0x80c2c778e3b73d33:0xbdc58662a4a97d49,None,34.058092,-118.292130,[Korean restaurant],4.4,18,None,"[[Thursday, 6:30AM–6PM], [Friday, 6:30AM–6PM],...","{'Service options': ['Takeout', 'Dine-in', 'De...",Open ⋅ Closes 6PM,"[0x80c2c78249aba68f:0x35bf16ce61be751d, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
3,Nova Fabrics,"Nova Fabrics, 2200 E 11th St, Los Angeles, CA ...",0x80c2c89923b27a41:0x32041559418d447,None,34.023669,-118.232930,[Fabric store],3.3,6,None,"[[Thursday, 9AM–5PM], [Friday, 9AM–5PM], [Satu...","{'Service options': ['In-store shopping'], 'Pa...",Open ⋅ Closes 5PM,"[0x80c2c8811477253f:0x23a8a492df1918f7, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
4,Nobel Textile Co,"Nobel Textile Co, 719 E 9th St, Los Angeles, C...",0x80c2c632f933b073:0xc31785961fe826a6,None,34.036694,-118.249421,[Fabric store],4.3,7,None,"[[Thursday, 9AM–5PM], [Friday, 9AM–5PM], [Satu...",{'Service options': ['In-store pickup']},Open ⋅ Closes 5PM,"[0x80c2c62c496083d1:0xdefa11317fe870a1, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...

In [3]:
df_2 = pd.read_json('C:/Users/tomas/Desktop/DS - HENRY/00.LABS/3.PF/GOOGLE/metadata-sitios/2.json', lines= True)
df_3 = pd.read_json('C:/Users/tomas/Desktop/DS - HENRY/00.LABS/3.PF/GOOGLE/metadata-sitios/3.json', lines= True)
df_4 = pd.read_json('C:/Users/tomas/Desktop/DS - HENRY/00.LABS/3.PF/GOOGLE/metadata-sitios/4.json', lines= True)
df_5 = pd.read_json('C:/Users/tomas/Desktop/DS - HENRY/00.LABS/3.PF/GOOGLE/metadata-sitios/5.json', lines= True)
df_6 = pd.read_json('C:/Users/tomas/Desktop/DS - HENRY/00.LABS/3.PF/GOOGLE/metadata-sitios/6.json', lines= True)
df_7 = pd.read_json('C:/Users/tomas/Desktop/DS - HENRY/00.LABS/3.PF/GOOGLE/metadata-sitios/7.json', lines= True)
df_8 = pd.read_json('C:/Users/tomas/Desktop/DS - HENRY/00.LABS/3.PF/GOOGLE/metadata-sitios/8.json', lines= True)
df_9 = pd.read_json('C:/Users/tomas/Desktop/DS - HENRY/00.LABS/3.PF/GOOGLE/metadata-sitios/9.json', lines= True)
df_10 = pd.read_json('C:/Users/tomas/Desktop/DS - HENRY/00.LABS/3.PF/GOOGLE/metadata-sitios/10.json', lines= True)
df_11 = pd.read_json('C:/Users/tomas/Desktop/DS - HENRY/00.LABS/3.PF/GOOGLE/metadata-sitios/11.json', lines= True)

In [4]:
# Create a list to store your DataFrames
dfs = []

# Assuming you have DataFrames named df1 through df18
for i in range(1, 12):
    # Assuming the variable names are df1, df2, ..., df18
    df = globals()[f'df_{i}']
    dfs.append(df)

# Concatenate all the DataFrames in the list
merged_df = pd.concat(dfs, ignore_index=True)

# The resulting merged_df contains data from all the DataFrames

In [5]:
merged_df.to_csv('Metadata.csv', index=False, escapechar='\\')

In [6]:
merged_df.shape

(3025011, 15)

In [7]:
merged_df.columns

Index(['name', 'address', 'gmap_id', 'description', 'latitude', 'longitude',
       'category', 'avg_rating', 'num_of_reviews', 'price', 'hours', 'MISC',
       'state', 'relative_results', 'url'],
      dtype='object')

In [8]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3025011 entries, 0 to 3025010
Data columns (total 15 columns):
 #   Column            Dtype
---  ------            -----
 0   name              object
 1   address           object
 2   gmap_id           object
 3   description       object
 4   latitude          float64
 5   longitude         float64
 6   category          object
 7   avg_rating        float64
 8   num_of_reviews    int64
 9   price             object
 10  hours             object
 11  MISC              object
 12  state             object
 13  relative_results  object
 14  url               object
dtypes: float64(3), int64(1), object(11)
memory usage: 346.2+ MB

In [9]:
metadata = pd.read_csv("C:/Users/tomas/Desktop/DS - HENRY/00.LABS/3.PF/GOOGLE/metadata-sitios/Metadata.csv")
metadata

,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,relative_results,url
0,Porter Pharmacy,"Porter Pharmacy, 129 N Second St, Cochran, GA ...",0x88f16e41928ff687:0x883dad4fd048e8f8,NaN,32.388300,-83.357100,['Pharmacy'],4.9,16,NaN,"[['Friday', '8AM–6PM'], ['Saturday', '8AM–12PM...","{'Service options': ['In-store shopping', 'Sam...",Open ⋅ Closes 6PM,"['0x88f16e41929435cf:0x5b2532a2885e9ef6', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
1,City Textile,"City Textile, 3001 E Pico Blvd, Los Angeles, C...",0x80c2c98c0e3c16fd:0x29ec8a728764fdf9,NaN,34.018891,-118.215290,['Textile exporter'],4.5,6,NaN,NaN,NaN,Open now,"['0x80c2c624136ea88b:0xb0315367ed448771', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
2,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",0x80c2c778e3b73d33:0xbdc58662a4a97d49,NaN,34.058092,-118.292130,['Korean restaurant'],4.4,18,NaN,"[['Thursday', '6:30AM–6PM'], ['Friday', '6:30A...","{'Service options': ['Takeout', 'Dine-in', 'De...",Open ⋅ Closes 6PM,"['0x80c2c78249aba68f:0x35bf16ce61be751d', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
3,Nova Fabrics,"Nova Fabrics, 2200 E 11th St, Los Angeles, CA ...",0x80c2c89923b27a41:0x32041559418d447,NaN,34.023669,-118.232930,['Fabric store'],3.3,6,NaN,"[['Thursday', '9AM–5PM'], ['Friday', '9AM–5PM'...","{'Service options': ['In-store shopping'], 'Pa...",Open ⋅ Closes 5PM,"['0x80c2c8811477253f:0x23a8a492df1918f7', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
4,Nobel Textile Co,"Nobel Textile Co, 719 E 9th St, Los Angeles, C...",0x80c2c632f933b073:0xc31785961fe826a6,NaN,34.036694,-118.249421,['Fabric store'],4.3,7,NaN,"[['Thursday', '9AM–5PM'], ['Friday', '9AM–5PM'...",{'Service options': ['In-store pickup']},Open ⋅ Closes 5PM,"['0x80c2c62c496083d1:0xdefa11317fe870a1', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3025006,Steak 48,"Steak 48, 260 S Broad St, Philadelphia, PA 19102",0x89c6c74f43a49b55:0x6be6995921c58b12,NaN,39.947254,-75.164953,"['Steak house', 'Fine dining restaurant', 'Sea...",4.6,308,NaN,"[['Monday', '4–10PM'], ['Tuesday', '4–10PM'], ...","{'Service options': ['Takeout', 'Dine-in', 'De...",Closed ⋅ Opens 4PM,"['0x89c6c7af1a55f4f9:0x589bb93addf7fd95', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
3025007,"Jack Mcnerney Chevrolet, Inc.","Jack Mcnerney Chevrolet, Inc., 363 NY-281, Tul...",0x89da1787d3fdc4a5:0xce92ea6e3cd4d1cc,NaN,42.788636,-76.122120,['Chevrolet dealer'],4.4,143,NaN,"[['Monday', '8:30AM–7PM'], ['Tuesday', '8:30AM...","{'Service options': ['In-store shopping'], 'Of...",Open ⋅ Closes 7PM,"['0x89d98d228469e435:0x3fdc4fa72594151', '0x89...",https://www.google.com/maps/place//data=!4m2!3...
3025008,Central Ny Spay Neuter Assista,"Central Ny Spay Neuter Assista, 17 Salisbury S...",0x89da6b9ce832726f:0xbd0d3630f1e3b42e,NaN,42.603831,-76.165286,['Veterinarian'],4.3,88,NaN,NaN,{'Planning': ['Appointments recommended']},Open now,"['0x89da6c67512700cb:0x69892b3a9a648efe', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
3025009,Ok Feed Store,"Ok Feed Store, 16300 SW 296th St, Homestead, F...",0x88d9e872a9e39f3d:0x5de29f50507e5d73,NaN,25.491641,-80.456076,['Animal feed store'],4.9,13,NaN,"[['Monday', '9AM–6PM'], ['Tuesday', '9AM–6PM']...","{'Service options': ['Curbside pickup', 'In-st...",Open ⋅ Closes 6PM,"['0x88d9e86cb955da7b:0xeda838b28926c524', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
3025010,Crestview Crossing,"Crestview Crossing, Newberg, OR 97132",0x54956b3944b1654d:0x7797cead9a485c22,NaN,45.310254,-122.935500,['Lodging'],5.0,1,NaN,NaN,{'Accessibility': ['Wheelchair accessible entr...,NaN,NaN,https://www.google.com/maps/place//data=!4m2!3...

In [10]:
reviews_fl= pd.read_csv("C:/Users/tomas/Desktop/DS - HENRY/00.LABS/3.PF/Florida.csv")
reviews_fl.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.014719e+20,Julie A. Gerber,1628003250740,1,Update: Their “reply” to my review amounted to...,NaN,"{'time': 1627042799532, 'text': 'Thank you for...",0x8893863ea87bd5dd:0x9383ebf973e74abb
1,1.154772e+20,Martin Sheffield,1595031217005,5,He's a knowledgeable doctor but the way he run...,NaN,"{'time': 1582464056733, 'text': 'Thank you for...",0x8893863ea87bd5dd:0x9383ebf973e74abb
2,1.018050e+20,Brian Truett,1522924253567,5,"Best doctor I've ever had, I never wait to be ...",NaN,NaN,0x8893863ea87bd5dd:0x9383ebf973e74abb
3,1.063444e+20,Tina Sun,1467907819586,1,I was told he is a good doctor. I was trying t...,NaN,NaN,0x8893863ea87bd5dd:0x9383ebf973e74abb
4,1.008751e+20,James Haynes,1480683415081,5,Takes the time to actually get to know his pat...,NaN,NaN,0x8893863ea87bd5dd:0x9383ebf973e74abb

In [11]:
reviews_fl.shape

(2850000, 8)

In [12]:
reviews_fl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2850000 entries, 0 to 2849999
Data columns (total 8 columns):
 #   Column   Dtype
---  ------   -----
 0   user_id  float64
 1   name     object
 2   time     int64
 3   rating   int64
 4   text     object
 5   pics     object
 6   resp     object
 7   gmap_id  object
dtypes: float64(1), int64(2), object(5)
memory usage: 174.0+ MB

In [13]:
reviews_fl_completo = pd.merge(reviews_fl, metadata, on='gmap_id', how='inner')

In [14]:
reviews_fl_completo.columns

Index(['user_id', 'name_x', 'time', 'rating', 'text', 'pics', 'resp',
       'gmap_id', 'name_y', 'address', 'description', 'latitude', 'longitude',
       'category', 'avg_rating', 'num_of_reviews', 'price', 'hours', 'MISC',
       'state', 'relative_results', 'url'],
      dtype='object')

In [15]:
reviews_fl_completo.to_csv('Reviews_FL_completo.csv', index=False, escapechar='\\')

In [16]:
reviews_fl_completo = pd.read_csv("C:/Users/tomas/Desktop/DS - HENRY/00.LABS/3.PF/GOOGLE/metadata-sitios/reviews_FL_completo.csv")
reviews_fl_completo

,user_id,name_x,time,rating,text,pics,resp,gmap_id,name_y,address,...,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,relative_results,url
0,1.014719e+20,Julie A. Gerber,1628003250740,1,Update: Their “reply” to my review amounted to...,NaN,"{'time': 1627042799532, 'text': 'Thank you for...",0x8893863ea87bd5dd:0x9383ebf973e74abb,"Brian Shaheen, MD","Brian Shaheen, MD, 2421 Thomas Dr, Panama City...",...,-85.752277,"['Family practice physician', 'General practit...",4.2,18,NaN,"[['Thursday', '8AM–5PM'], ['Friday', '8AM–5PM'...","{'Service options': ['Online care'], 'Accessib...",Open ⋅ Closes 5PM,"['0x88938ebfbd53f9c5:0xf6e52004f37523c8', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
1,1.014719e+20,Julie A. Gerber,1628003250740,1,Update: Their “reply” to my review amounted to...,NaN,"{'time': 1627042799532, 'text': 'Thank you for...",0x8893863ea87bd5dd:0x9383ebf973e74abb,"Brian Shaheen, MD","Brian Shaheen, MD, 2421 Thomas Dr, Panama City...",...,-85.752277,"['Family practice physician', 'General practit...",4.2,18,NaN,"[['Thursday', '8AM–5PM'], ['Friday', '8AM–5PM'...","{'Service options': ['Online care'], 'Accessib...",Open ⋅ Closes 5PM,"['0x88938ebfbd53f9c5:0xf6e52004f37523c8', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
2,1.154772e+20,Martin Sheffield,1595031217005,5,He's a knowledgeable doctor but the way he run...,NaN,"{'time': 1582464056733, 'text': 'Thank you for...",0x8893863ea87bd5dd:0x9383ebf973e74abb,"Brian Shaheen, MD","Brian Shaheen, MD, 2421 Thomas Dr, Panama City...",...,-85.752277,"['Family practice physician', 'General practit...",4.2,18,NaN,"[['Thursday', '8AM–5PM'], ['Friday', '8AM–5PM'...","{'Service options': ['Online care'], 'Accessib...",Open ⋅ Closes 5PM,"['0x88938ebfbd53f9c5:0xf6e52004f37523c8', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
3,1.154772e+20,Martin Sheffield,1595031217005,5,He's a knowledgeable doctor but the way he run...,NaN,"{'time': 1582464056733, 'text': 'Thank you for...",0x8893863ea87bd5dd:0x9383ebf973e74abb,"Brian Shaheen, MD","Brian Shaheen, MD, 2421 Thomas Dr, Panama City...",...,-85.752277,"['Family practice physician', 'General practit...",4.2,18,NaN,"[['Thursday', '8AM–5PM'], ['Friday', '8AM–5PM'...","{'Service options': ['Online care'], 'Accessib...",Open ⋅ Closes 5PM,"['0x88938ebfbd53f9c5:0xf6e52004f37523c8', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
4,1.018050e+20,Brian Truett,1522924253567,5,"Best doctor I've ever had, I never wait to be ...",NaN,NaN,0x8893863ea87bd5dd:0x9383ebf973e74abb,"Brian Shaheen, MD","Brian Shaheen, MD, 2421 Thomas Dr, Panama City...",...,-85.752277,"['Family practice physician', 'General practit...",4.2,18,NaN,"[['Thursday', '8AM–5PM'], ['Friday', '8AM–5PM'...","{'Service options': ['Online care'], 'Accessib...",Open ⋅ Closes 5PM,"['0x88938ebfbd53f9c5:0xf6e52004f37523c8', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2869641,1.039909e+20,J. B. Oliveira,1503293272680,5,It is a buyers paradise. Hundred places inside...,NaN,NaN,0x88d908feeaeded1f:0x29c1bf6101ce3a42,Sawgrass Mills,"Sawgrass Mills, 12801 W Sunrise Blvd, Sunrise,...",...,-80.323482,['Shopping mall'],4.6,9998,NaN,"[['Tuesday', '10AM–9PM'], ['Wednesday', '10AM–...","{'Service options': ['In-store shopping'], 'Ac...",Open ⋅ Closes 9PM,"['0x88d908e2cc3ae13d:0xdc423c508b26297a', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
2869642,1.124797e+20,Adam K,1514763473117,5,Great place to go especially if you're in the ...,NaN,NaN,0x88d908feeaeded1f:0x29c1bf6101ce3a42,Sawgrass Mills,"Sawgrass Mills, 12801 W Sunrise Blvd, Sunrise,...",...,-80.323482,['Shopping mall'],4.6,9998,NaN,"[['Tuesday', '10AM–9PM'], ['Wednesday', '10AM–...","{'Service options': ['In-store shopping'], 'Ac...",Open ⋅ Closes 9PM,"['0x88d908e2cc3ae13d:0xdc423c508b26297a', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
2869643,1.103771e+20,English People,1531250213447,5,I love this place so much and come here alot a...,NaN,NaN,0x88d908feeaeded1f:0x29c1bf6101ce3a42,Sawgrass Mills,"Sawgrass Mills, 12801 W Sunrise Blvd, Sunrise,...",...,-80.323482,['Shopping mall'],4.6,9998,NaN,"[['Tuesday', '10AM–9PM'], ['Wednesday', '10AM–...","{'Service options': ['In-store shopping'], 'Ac...",Open ⋅ Closes 9PM,"['0x88d908e2cc3ae13d:0xdc423c508b26297a', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
2869644,1.099194e+20,Shiva K,1532621720862,4,"Plenty of shops with excellent variety, ample ...",NaN,NaN,0x88d908feeaeded1f:0x29c1bf6101ce3a42,Sawgrass Mills,"Sawgrass Mills, 12801 W Sunrise Blvd, Sunrise,...",...,-80.323482,['Shopping mall'],4.6,9998,NaN,"[['Tuesday', '10AM–9PM'], ['Wednesday', '10AM–...","{'Service options': ['In-store shopping'], 'Ac...",Open ⋅ Closes 9PM,"['0x88d908e2cc3ae13d:0xdc423c508b26297a', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
2869645,1.160935e+20,Tiago nascimento,1577461433361,4,Nice open mall,NaN,NaN,0x88d908feeaeded1f:0x29c1bf6101ce3a42,Sawgrass Mills,"Sawgrass Mills, 12801 W Sunrise Blvd, Sunrise,...",...,-80.323482,['Shopping mall'],4.6,9998,NaN,"[['Tuesday', '10AM–9PM'], ['Wednesday', '10AM–...","{'Service options': ['In-store shopping'], 'Ac...",Open ⋅ Closes 9PM,"['0x88d908e2cc3ae13d:0xdc423c508b26297a', '0x8...",https://www.google.com/maps/place//data=!4m2!3...

In [17]:
reviews_fl_completo.shape

(2869646, 22)

In [18]:
reviews_fl_completo.name_y.nunique()

48997

In [19]:
#import folium
#import pandas as pd


# Create a map centered at a specific location (e.g., the first location)
#m = folium.Map(location=[reviews_fl["latitude"].iloc[0], reviews_fl["longitude"].iloc[0]], zoom_start=12)

# Iterate over the DataFrame and add markers for each location
#for index, row in reviews_fl.iterrows():
#    folium.Marker(
#        location=[row["latitude"], row["longitude"]],
#        popup=row["name_x"],
#        icon=folium.Icon(icon='cloud')
#    ).add_to(m)

# Display the map
#m

In [20]:
reviews_fl_completo.columns

Index(['user_id', 'name_x', 'time', 'rating', 'text', 'pics', 'resp',
       'gmap_id', 'name_y', 'address', 'description', 'latitude', 'longitude',
       'category', 'avg_rating', 'num_of_reviews', 'price', 'hours', 'MISC',
       'state', 'relative_results', 'url'],
      dtype='object')

In [21]:
pivot_table = reviews_fl_completo.pivot_table(index=['name_y', 'latitude', 'longitude'], values='gmap_id', aggfunc='count').reset_index()

# Rename the 'review_id' column to 'review_count' (optional)
pivot_table = pivot_table.rename(columns={'gmap_id': 'review_count'})

# Display the pivot table
pivot_table

,name_y,latitude,longitude,review_count
0,"""Public Library And Student Main Parking Garage""",26.081129,-80.242743,13
1,#1 Anytime Bail 24/7,29.197376,-82.163098,10
2,#1 Nails,28.755290,-81.356828,23
3,#1 Stop Grocery & Market,30.345278,-81.675278,31
4,#1 auto liquidators,30.630575,-81.574254,10
...,...,...,...,...
59187,💨 3J's Cigar Davie,26.063887,-80.257336,59
59188,💨 3J's Cigar Lake Worth,26.618506,-80.159312,31
59189,💳 Credit360 Credit Repair Services 📈,25.595703,-80.363983,24
59190,😁 White Smiles of Boca,26.350016,-80.090242,27
59191,🥇 Nectar Lab Kava Bar,26.176886,-81.799163,46

In [22]:
pivot_table

,name_y,latitude,longitude,review_count
0,"""Public Library And Student Main Parking Garage""",26.081129,-80.242743,13
1,#1 Anytime Bail 24/7,29.197376,-82.163098,10
2,#1 Nails,28.755290,-81.356828,23
3,#1 Stop Grocery & Market,30.345278,-81.675278,31
4,#1 auto liquidators,30.630575,-81.574254,10
...,...,...,...,...
59187,💨 3J's Cigar Davie,26.063887,-80.257336,59
59188,💨 3J's Cigar Lake Worth,26.618506,-80.159312,31
59189,💳 Credit360 Credit Repair Services 📈,25.595703,-80.363983,24
59190,😁 White Smiles of Boca,26.350016,-80.090242,27
59191,🥇 Nectar Lab Kava Bar,26.176886,-81.799163,46

In [25]:
reviews_fl_completo_with_text = reviews_fl_completo[reviews_fl_completo["text"].notna()]

In [26]:
reviews_fl_completo_with_text.name_x.value_counts()

A Google User     787
Chris             281
John              280
Mike              279
David             270
                 ...
Magaly Nelson       1
magznolia           1
Geraof geraof       1
Martha Laynes       1
English People      1
Name: name_x, Length: 590197, dtype: int64